src/Entity/Attestation.php
<?php

namespace App\Entity;

use App\Repository\AttestationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AttestationRepository::class)]
class Attestation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $TypeAttestation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateDemmande = null;

    #[ORM\Column]
    private ?bool $Statue = null;

    #[ORM\ManyToOne(inversedBy: 'Attestation')]
    private ?Employe $employe = null;

    #[ORM\ManyToOne(inversedBy: 'Attestation')]
    private ?User $user = null;
    public function __construct()
    {
        $this->DateDemmande = new \DateTime('now');
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeAttestation(): ?string
    {
        return $this->TypeAttestation;
    }

    public function setTypeAttestation(string $TypeAttestation): self
    {
        $this->TypeAttestation = $TypeAttestation;

        return $this;
    }

    public function getDateDemmande(): ?\DateTimeInterface
    {
        return $this->DateDemmande;
    }

    public function setDateDemmande(\DateTimeInterface $DateDemmande): self
    {
        $this->DateDemmande = $DateDemmande;

        return $this;
    }

    public function isStatue(): ?bool
    {
        return $this->Statue;
    }

    public function setStatue(bool $Statue): self
    {
        $this->Statue = $Statue;

        return $this;
    }

    public function getEmploye(): ?Employe
    {
        return $this->employe;
    }

    public function setEmploye(?Employe $employe): self
    {
        $this->employe = $employe;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: Role::class, inversedBy: 'users')]
    private Collection $Role;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Fonction = null;

    #[ORM\Column(length: 255)]
    private ?string $Departement = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Attestation::class)]
    private Collection $Attestation;

    public function __construct()
    {
        $this->Role = new ArrayCollection();
        $this->Attestation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $userRoles = $this->getRole();
       
        foreach ($userRoles as $userRole) {
            $roles[]=$userRole->getRoleName();
        }
        
      return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getRole(): Collection
    {
        return $this->Role;
    }

    public function addRole(Role $role): self
    {
        if (!$this->Role->contains($role)) {
            $this->Role->add($role);
        }

        return $this;
    }

    public function removeRole(Role $role): self
    {
        $this->Role->removeElement($role);

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->Fonction;
    }

    public function setFonction(?string $Fonction): self
    {
        $this->Fonction = $Fonction;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->Departement;
    }

    public function setDepartement(string $Departement): self
    {
        $this->Departement = $Departement;

        return $this;
    }

    /**
     * @return Collection<int, Attestation>
     */
    public function getAttestation(): Collection
    {
        return $this->Attestation;
    }

    public function addAttestation(Attestation $attestation): self
    {
        if (!$this->Attestation->contains($attestation)) {
            $this->Attestation->add($attestation);
            $attestation->setUser($this);
        }

        return $this;
    }

    public function removeAttestation(Attestation $attestation): self
    {
        if ($this->Attestation->removeElement($attestation)) {
            // set the owning side to null (unless already changed)
            if ($attestation->getUser() === $this) {
                $attestation->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/AttestationController.php
<?php

namespace App\Controller;

use App\Entity\Attestation;
use App\Form\Attestation1Type;
use App\Repository\AttestationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user/Attestation')]
class AttestationController extends AbstractController
{
    
    #[Route('/', name: 'app_attestation_index', methods: ['GET'])]
    public function index(AttestationRepository $attestationRepository): Response
    {
        return $this->render('attestation/index.html.twig', [
            'attestations' => $attestationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_attestation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AttestationRepository $attestationRepository): Response
    {
        $attestation = new Attestation();
        $form = $this->createForm(Attestation1Type::class, $attestation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $attestationRepository->save($attestation, true);

            return $this->redirectToRoute('app_attestation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('attestation/new.html.twig', [
            'attestation' => $attestation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_attestation_show', methods: ['GET'])]
    public function show(Attestation $attestation): Response
    {
        return $this->render('attestation/show.html.twig', [
            'attestation' => $attestation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_attestation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Attestation $attestation, AttestationRepository $attestationRepository): Response
    {
        $form = $this->createForm(Attestation1Type::class, $attestation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $attestationRepository->save($attestation, true);

            return $this->redirectToRoute('app_attestation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('attestation/edit.html.twig', [
            'attestation' => $attestation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_attestation_delete', methods: ['POST'])]
    public function delete(Request $request, Attestation $attestation, AttestationRepository $attestationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$attestation->getId(), $request->request->get('_token'))) {
            $attestationRepository->remove($attestation, true);
        }

        return $this->redirectToRoute('app_attestation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/attestation/_delete_form.html.twig
<form method="post" action="{{ path('app_attestation_delete', {'id': attestation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ attestation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/attestation/_form.html.twig
{{ form_start(form) }}

    <p> Nom Complet:  {{app.user.Nom}} {{app.user.prenom}}</p></center><br>
    {{ form_row(form.TypeAttestation,{'attr':{'class':'form-control'}})}} 
								<br>
  {# {{ form_row(form.Nom,{'attr':{'class':'form-control'}})}} <br>
  {{ form_row(form.Prenom,{'attr':{'class':'form-control'}})}} <br> #}
    <button class="btn btn-warning">{{ button_label|default('Demandée') }}</button>
{{ form_end(form) }}

templates/attestation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Attestation{% endblock %}

{% block body %}
    <h1>Edit Attestation</h1>

    {{ include('attestation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_attestation_index') }}">back to list</a>

    {{ include('attestation/_delete_form.html.twig') }}
{% endblock %}

templates/attestation/index.html.twig
{% extends 'navUser.html.twig' %}

{% block title %}RH Tracker{% endblock %}

{% block body %}
   
   
<div class="row">
<div class="col-md-5 col-xl-12">
                       
							<div class="card ">
								<div class="card-header">

									<h5 class="card-title mb-0">Demande des piéces administratif</h5>
								</div>
 
<div class="card-body h-100">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Type Attestation</th>
                <th>Date Demande</th>
                <th>Etat</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for attestation in attestations %}
            <tr>
                <td>{{ attestation.id }}</td>
                <td>{{ attestation.TypeAttestation }}</td>
                <td>{{ attestation.DateDemmande ? attestation.DateDemmande|date('Y-m-d') : '' }}</td>
                {# <td>{{ attestation.Statue ? 'Validé' : 'En cours' }}</td> #}
                <td>{% if((attestation.Statue)=="Yes") %}
                <svg style="color:green;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
  <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
</svg>
                  <!--  <i class="align-middle me-2" data-feather="eye"></i>-->
                {% else %}
                    <svg style="color:red;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
  <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
</svg>
             <!-- <i class="align-middle me-2" data-feather="lock"></i>-->
                
                {% endif %}</td>
                <td>
                    <a href="{{ path('app_attestation_show', {'id': attestation.id}) }}" style="color:#0071BC;"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
  <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
</svg></a>
                 
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun Pièce à été demandé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</div>

{% endblock %}

templates/attestation/new.html.twig
{% extends 'navUser.html.twig' %}

{% block title %}RH Tracker{% endblock %}

{% block body %}
   
   <style>
.center_div{
    margin: 0 auto;
    width:50% ;/* value of your choice which suits your alignment */
    background:white;
   box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
   
}
</style>
<div class="container center_div">
							<div class="card-body">
								<div class="m-sm-4">
                                 <h4>Demande des pièces</h4>
<br>


    {{ include('attestation/_form.html.twig') }}

</div>
    </div></div>
{% endblock %}

templates/attestation/show.html.twig
{% extends 'navUser.html.twig' %}

{% block title %}Attestation{% endblock %}

{% block body %}
   <style>
.center_div{
    margin: 0 auto;
    width:50% ;/* value of your choice which suits your alignment */
    background:white;
   box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
   
}
</style>
<div class="container center_div">
							<div class="card-body">
								<div class="m-sm-4">
                                <center><u>
                                 <h3>Détails</h3></u></center>
<br>
    <table class="table">
        <tbody>
            
            <tr>
                <th>Type Attestation</th>
                <td>{{ attestation.TypeAttestation }}</td>
            </tr>
            <tr>
                <th>Date Demande</th>
                <td>{{ attestation.DateDemmande ? attestation.DateDemmande|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                {# <td>{{ attestation.Statue ? 'Valide' : 'En cours' }}</td> #}
                <td>
                {% if((attestation.Statue)=="Yes") %}
                <svg style="color:green;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar2-check" viewBox="0 0 16 16">
  <path d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2z"/>
  <path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V4z"/>
</svg>
                  <!--  <i class="align-middle me-2" data-feather="eye"></i>-->
                {% else %}
                    <svg style="color:red;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-x" viewBox="0 0 16 16">
  <path d="M6.146 7.146a.5.5 0 0 1 .708 0L8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 0 1 0-.708z"/>
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
</svg>
             <!-- <i class="align-middle me-2" data-feather="lock"></i>-->
                
                {% endif %}</td>
            </tr>
             
        </tbody>
    </table>

    </div>
    </div></div>
{% endblock %}